name: morphem70k
img_size: 224
root_dir: /projectnb/cs598/projects/Modalities_Robustness/channel_adaptive_models/chammi_dataset/CHAMMI/
file_name: /projectnb/cs598/students/ayak/diverse_channel_vit/metadata/morphem70k_v2.csv
in_channel_names: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
