name: morphem70k
img_size: 224
#root_dir: /projectnb/morphem/data_70k/ver2/morphem_70k_version2/
#root_dir: /projectnb/cs598/projects/Modalities_Robustness/diverse_channel_vit/metadata/
root_dir: /projectnb/cs598/projects/Modalities_Robustness/channel_adaptive_models/chammi_dataset/CHAMMI/
#file_name: morphem70k_v2.csv 
file_name: /projectnb/cs598/projects/Modalities_Robustness/channel_adaptive_models/chammi_dataset/morphem70k_v2.csv
in_channel_names: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]



