hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params:
      train: random_instance
      data_chunk: morphem70k
      model: convnext_base
      scheduler: cosine
      optimizer: adamw
      dataset: morphem70k_v2
      logging: wandb
      hardware: default
      eval: default
      attn_pooling: none
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - model=dichavit
    - dataset=morphem70k_v2_12channels
    - tag=morphem_dichavit_leave_one_out
    - ++eval.eval_subset_channels=False
    - ++eval.eval_leave_one_out_channels=True
    - ++train.checkpoint_path=/projectnb/cs598/projects/Modalities_Robustness/adaptive_channel_strategy/checkpoints/morphem70k/2025-Mar-27-14-31-39--seed2025/model_last.pt
    - ++train.resume=True
    - ++train.resume_only_model=True
    - ++eval.batch_size=64
    - ++model.new_channel_inits=[zero]
    - ++model.enable_sample=True
    - ++logging.wandb.run_name=morphem_dichavit_channel_importance_2025-04-08_15-31-37
  job:
    name: main
    chdir: null
    override_dirname: ++eval.batch_size=64,++eval.eval_leave_one_out_channels=True,++eval.eval_subset_channels=False,++logging.wandb.run_name=morphem_dichavit_channel_importance_2025-04-08_15-31-37,++model.enable_sample=True,++model.new_channel_inits=[zero],++train.checkpoint_path=/projectnb/cs598/projects/Modalities_Robustness/adaptive_channel_strategy/checkpoints/morphem70k/2025-Mar-27-14-31-39--seed2025/model_last.pt,++train.resume=True,++train.resume_only_model=True,dataset=morphem70k_v2_12channels,model=dichavit,tag=morphem_dichavit_leave_one_out
    id: ???
    num: ???
    config_name: chammi_cfg
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /projectnb/cs598/projects/Modalities_Robustness/adaptive_channel_strategy_aya/diverse_channel_vit
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /projectnb/cs598/projects/Modalities_Robustness/adaptive_channel_strategy_aya/diverse_channel_vit/configs
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      attn_pooling: null
      eval: null
      hardware: null
      logging: null
      data_chunk: null
      dataset: morphem70k_v2_12channels
      optimizer: null
      scheduler: null
      model: dichavit
      train: null
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
model:
  name: dichavit
  pretrained: false
  pretrained_model_name: small
  in_dim: null
  num_classes: null
  pooling: avg
  temperature: 0.11111
  learnable_temp: false
  unfreeze_last_n_layers: -1
  unfreeze_first_layer: true
  init_first_layer: null
  reset_last_n_unfrozen_layers: false
  enable_sample: true
  in_channel_names: FILL_LATER
  new_channel_inits:
  - zero
  use_channelvit_channels: true
  patch_size: 16
  orthogonal_channel_emb_init: false
  dropout_tokens_hcs: none
  freeze_channel_emb: false
  keep_rate: null
  block_type: block
  hcs_sampling: none
  hcs_sampling_temp: 0.1
  proxy_loss_lambda: 0
  ortho_loss_v1_lambda: 0
  drop_path_rate: 0.0
  gamma_s: 1.0
  gamma_d: 0.5
  reverse_pos_pairs: false
  use_square: false
dataset:
  name: morphem70k
  img_size: 224
  root_dir: /projectnb/cs598/projects/Modalities_Robustness/channel_adaptive_models/chammi_dataset/CHAMMI/
  file_name: /projectnb/cs598/students/ayak/diverse_channel_vit/metadata/morphem70k_v2.csv
  in_channel_names:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
tag: morphem_dichavit_leave_one_out
eval:
  eval_subset_channels: false
  eval_leave_one_out_channels: true
  batch_size: 64
train:
  checkpoint_path: /projectnb/cs598/projects/Modalities_Robustness/adaptive_channel_strategy/checkpoints/morphem70k/2025-Mar-27-14-31-39--seed2025/model_last.pt
  resume: true
  resume_only_model: true
logging:
  wandb:
    run_name: morphem_dichavit_channel_importance_2025-04-08_15-31-37
